import React from "react";

export const defaultColorsUsed = [
    {
        title:'Toasty Web Project',
        link:'/Project/Toasty',
        colors:['aliceBlue', 'Orange', 'steelBlue', 'Wheat']
    },
]

export const defaultColors = [
    {color:'AliceBlue', hex:'#F0F8FF', used:true, palette:'Toasty' }, 
    {color:'AntiqueWhite', hex:'#FAEBD7', used:false},
    {color: 'Aqua', hex:'#00FFFF', used:false},
    {color: 'Aquamarine', hex:'#7FFFD4', used:false},
    {color: 'Azure', hex:'#F0FFFF', used:false},
    {color: 'Beige', hex:'#F5F5DC', used:false},
    {color: 'Bisque', hex:'#FFE4C4', used:false},
    {color:'Black', hex:'#000000', used:false},
    {color:'BlanchedAlmond', hex:'#FFEBCD', used:false},
    {color:'Blue', hex:'#0000FF', used:false},
    {color:'BlueViolet', hex:'#8A2BE2', used:false},
    {color:'Brown', hex:'#A52A2A', used:false},
    {color:'BurlyWood', hex:'#DEB887', used:false},
    {color:'CadetBlue', hex:'#5F9EA0', used:false},
    {color:'Chartreuse', hex:'#7FFF00', used:false},
    {color:'Chocolate', hex:'#D2691E', used:false},
    {color:'Coral', hex:'#FF7F50', used:false},
    {color:'CornflowerBlue', hex:'#6495ED', used:false},
    {color:'Cornsilk', hex:'#FFF8DC', used:false},
    {color:'Crimson', hex:'#DC143C', used:false},
    {color:'Cyan', hex:'#00FFFF', used:false},
    {color:'DarkBlue', hex:'#00008B', used:false},
    {color:'DarkCyan', hex:'#008B8B', used:false},
    {color:'DarkGoldenRod', hex:'#B8860B', used:false},
    {color:'DarkGray', hex:'#A9A9A9', used:false},
    {color:'DarkGrey', hex:'#A9A9A9', used:false},
    {color:'DarkGreen', hex:'#006400', used:false},
    {color:'DarkKhaki', hex:'#BDB76B', used:false},
    {color:'DarkMagenta', hex:'#8B008B', used:false},
    {color:'DarkOliveGreen', hex:'#556B2F', used:false},
    {color:'DarkOrange', hex:'#FF8C00', used:false},
    {color:'DarkOrchid', hex:'#9932CC', used:false},
    {color:'DarkRed', hex:'#8B0000', used:false},
    {color:'DarkSalmon', hex:'#E9967A', used:false},
    {color:'DarkSeaGreen',hex:'#8FBC8F', used:false},
    {color:'DarkSlateBlue', hex:'#483D8B', used:false},
    {color:'DarkSlateGray', hex:'#2F4F4F', used:false},
    {color:'DarkSlateGrey', hex:'#2F4F4F', used:false},
    {color:'DarkTurquoise', hex:'#00CED1', used:false},
    {color:'DarkViolet', hex:'#9400D3', used:false},
    {color:'DeepPink', hex:'#FF1493', used:false},
    {color:'DeepSkyBlue', hex:'#00BFFF', used:false},
    {color:'DimGray', hex:'#696969', used:false},
    {color:'DimGrey', hex:'#696969', used:false},
    {color:'DodgerBlue', hex:'#1E90FF', used:false},
    {color:'FireBrick', hex:'#B22222', used:false},
    {color:'FloralWhite', hex:'#FFFAF0', used:false},
    {color:'ForestGreen', hex:'#228B22', used:false},
    {color:'Fuchsia', hex:'#FF00FF', used:false},
    {color:'Gainsboro', hex:'#DCDCDC', used:false},
    {color:'GhostWhite', hex:'#F8F8FF', used:false},
    {color:'Gold', hex:'#FFD700', used:false},
    {color:'GoldenRod', hex:'#DAA520', used:false},
    {color:'Gray', hex:'#808080', used:false},
    {color:'Grey', hex:'#808080', used:false},
    {color:'Green', hex:'#008000', used:false},
    {color:'GreenYellow', hex:'#ADFF2F', used:false},
    {color:'HoneyDew', hex:'#F0FFF0', used:false},
    {color:'HotPink', hex:'#FF69B4', used:false},
    {color:'IndianRed', hex:'#CD5C5C', used:false},
    {color:'Indigo', hex:'#4B0082', used:false},
    {color:'Ivory', hex:'#FFFFF0', used:false},
    {color:'Khaki', hex:'#F0E68C', used:false},
    {color:'Lavender', hex:'#E6E6FA', used:false},
    {color:'LavenderBlush', hex:'#FFF0F5', used:false},
    {color:'LawnGreen', hex:'#7CFC00', used:false},
    {color:'LemonChiffon', hex:'#FFFACD', used:false},
    {color:'LightBlue', hex:'#ADD8E6', used:false},
    {color:'LightCoral', hex:'#F08080', used:false},
    {color:'LightCyan', hex:'#E0FFFF', used:false},
    {color:`LightGoldenRodYellow`, hex:'#FAFAD2', used:false},
    {color:'LightGray', hex:'#D3D3D3', used:false},
    {color:'LightGrey', hex:'#D3D3D3', used:false},
    {color:'LightGreen', hex:'#90EE90', used:false},
    {color:'LightPink', hex:'#FFB6C1', used:false},
    {color:'LightSalmon', hex:'#FFA07A', used:false},
    {color:'LightSeaGreen', hex:'#20B2AA', used:false},
    {color:'LightSkyBlue', hex:'#87CEFA', used:false},
    {color:'LightSlateGray', hex:'#778899', used:false},
    {color:'LightSlateGrey', hex:'#778899', used:false},
    {color:'LightSteelBlue', hex:'#B0C4DE', used:false},
    {color:'LightYellow', hex:'#FFFFE0', used:false},
    {color:'Lime', hex:'#00FF00', used:false},
    {color:'LimeGreen', hex:'#32CD32', used:false},
    {color:'Linen', hex:'#FAF0E6', used:false},
    {color:'Magenta', hex:'#FF00FF', used:false},
    {color:'Maroon', hex:'#800000', used:false},
    {color:'MediumAquaMarine', hex:'#66CDAA', used:false},
    {color:'MediumBlue', hex:'#0000CD', used:false},
    {color:'MediumOrchid', hex:'#BA55D3', used:false},
    {color:'MediumPurple', hex:'#9370DB', used:false},
    {color:'MediumSeaGreen', hex:'#3CB371', used:false},
    {color:'MediumSlateBlue', hex:'#7B68EE', used:false},
    {color:'MediumSpringGreen', hex:'#00FA9A', used:false},
    {color:'MediumTurquoise', hex:'#48D1CC', used:false},
    {color:'MediumVioletRed', hex:'#C71585', used:false},
    {color:'MidnightBlue', hex:'#191970', used:false},
    {color:'MintCream', hex:'#F5FFFA', used:false},
    {color:'MistyRose', hex:'#FFE4E1', used:false},
    {color:'Moccasin', hex:'#FFE4B5', used:false},
    {color:'NavajoWhite', hex:'#FFDEAD', used:false},
    {color:'Navy', hex:'#000080', used:false},
    {color:'OldLace', hex:'#FDF5E6', used:false},
    {color:'Olive', hex:'#808000', used:false},
    {color:'OliveDrab', hex:'#6B8E23', used:false},
    {color:'Orange', hex:'#FFA500', used:true, palette:'Toasty'},
    {color:'OrangeRed', hex:'#FF4500', used:false},
    {color:'Orchid', hex:'#DA70D6', used:false},
    {color:'PaleGoldenRod', hex:'#EEE8AA', used:false},
    {color:'PaleGreen', hex:'#98FB98', used:false},
    {color:'PaleTurquoise', hex:'#AFEEEE', used:false},
    {color:'PaleVioletRed', hex:'#DB7093', used:false},
    {color:'PapayaWhip', hex:'#FFEFD5', used:false},
    {color:'PeachPuff', hex:'#FFDAB9', used:false},
    {color:'Peru', hex:'#CD853F', used:false},
    {color:'Pink', hex:'#FFC0CB', used:false},
    {color:'Plum', hex:'#DDA0DD', used:false},
    {color:'PowderBlue', hex:'#B0E0E6', used:false},
    {color:'Purple', hex:'#800080', used:false},
    {color:'RebeccaPurple', hex:'#663399', used:false},
    {color:'Red', hex:'#FF0000', used:false},
    {color:'RosyBrown', hex:'#BC8F8F', used:false},
    {color:'RoyalBlue', hex:'#4169E1', used:false},
    {color:'SaddleBrown', hex:'#8B4513', used:false},
    {color:'Salmon', hex:'#FA8072', used:false},
    {color:'SandyBrown', hex:'#F4A460', used:false},
    {color:'SeaGreen', hex:'#2E8B57', used:false},
    {color:'SeaShell', hex:'#FFF5EE', used:false},
    {color:'Sienna', hex:'#A0522D', used:false},
    {color:'Silver', hex:'#C0C0C0', used:false},
    {color:'SkyBlue', hex:'#87CEEB', used:false},
    {color:'SlateBlue', hex:'#6A5ACD', used:false},
    {color:'SlateGray', hex:'#708090', used:false},
    {color:'SlateGrey', hex:'#708090', used:false},
    {color:'Snow', hex:'#FFFAFA', used:false},
    {color:'SpringGreen', hex:'#00FF7F', used:false},
    {color:'SteelBlue', hex:'#4682B4', used:true, palette:'Toasty'},
    {color:'Tan', hex:'#D2B48C', used:false},
    {color:'Teal', hex:'#008080'},
    {color:'Thistle', hex:'#D8BFD8', used:false},
    {color:'Tomato', hex:'#FF6347', used:false},
    {color:'Turquoise', hex:'#40E0D0', used:false},
    {color:'Violet', hex:'#EE82EE', used:false},
    {color:'Wheat', hex:'#F5DEB3', used:true, palette:'Toasty'},
    {color:'White', hex:'#FFFFFF', used:false},
    {color:'WhiteSmoke', hex:'#F5F5F5', used:false},
    {color:'Yellow', hex:'#FFFF00', used:false},
    {color:'YellowGreen', hex:'#9ACD32', used:false}

]